site:
    title: "视角杂志"
    subtitle: "世界的不同维度"
    limit: 10
    theme: theme
    lang: zh
    url: "http://www.chole.io/blog"
    comment: perspicere
    logo: "-/images/logo.png"
    # link: "{category}/{year}/{month}/{day}/{title}.html"
    # root: "/content"

authors:
    perspicere:
        name: "视角杂志"
        intro: "世界的不同维度"
        avatar: "-/images/logo.png"
    z:
        name: 'Z'
        intro: '建筑学学生'
    huaxia:
        name: "华夏"
    yunze:
        name: "一枚读书匠"
        intro: "一只文艺的哲学猫"
        avatar: "-/images/avatars/yunze.jpeg"
    ruowang:
        name: "若望"
    yuteng:
        name: "曹雨腾"
        intro: "人文引导技术，技术赋能个体"
        avatar: "-/images/avatars/yuteng.jpg"
    ruyue:
        name: "姜如月"
    zimo:
        name: '杨子墨'
    houshang:
        name: '后商'
    plus_tard:
        name: '王美苏'
        intro: "一只会想象的草履虫。"
        avatar: "-/images/avatars/plus_tard.jpg"
    yuhe:
        name: '于翮'

build:
    output: "docs"
    port: 8000
    # Copied files to public folder when build
    copy:
        - "source/images"
        - "source/CNAME"
    # Excuted command when use 'ink publish'
    publish: |
        git add . -A
        git commit -m "update"
        git push origin
