site:
    title: "视角杂志"
    subtitle: "世界的不同维度"
    limit: 10
    theme: theme
    lang: zh
    url: "http://www.chole.io/blog"
    comment: perspicere
    logo: "-/images/logo.png"
    # link: "{category}/{year}/{month}/{day}/{title}.html"
    # root: "/content"

authors:
    me:
        name: "纸小墨"
        intro: "构建只为纯粹书写的博客"
        avatar: "-/images/avatars/avatar.png"
    ruowang:
        name: "若望"
        intro: "test"
        avator: "-/images/logo.png"
    yuteng:
        name: "曹雨腾"
    ruyue:
        name: "姜如月"
    zimo:
        name: '杨子墨'
    houshang:
        name: '后商'
    meisu:
        name: '王美苏'
    yuhe:
        name: '于翮'

build:
    output: "docs"
    port: 8000
    # Copied files to public folder when build
    copy:
        - "source/images"
        - "CNAME"
    # Excuted command when use 'ink publish'
    publish: |
        git add . -A
        git commit -m "update"
        git push origin
